version: 2
run:
  timeout: 3m
  tests: true

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gocritic
    - revive      
    - misspell      
    - errorlint     
    - nilerr        
    - unconvert     

linters-settings:
  revive:
    rules:
      - name: exported
        arguments: ["disableStutteringCheck"]
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
 